services:

  db:
    image: mariadb
    restart: always
    networks:
      - back_demo 
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mysmartrootpassword
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal

  phpmyadmin:
    image: phpmyadmin
    networks:
      - back_demo
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

  drupal:
    image: mihaimiculescu/drupal_commerce_kickstart_3
    networks:
      - front_demo
      - back_demo
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./modules:/opt/drupal/web/modules
      - ./profiles:/opt/drupal/web/profiles
      - ./themes:/opt/drupal/web/themes
      - ./sites:/opt/drupal/web/sites
      - ./private:/opt/drupal/private
    restart: always

volumes:
  db:
  modules:
  profiles:
  themes:
  sites:
  private:

networks:
  front_demo: {}
  back_demo: {}
  
