services:

  db:
    image: mariadb
    container_name: mariadbdemo
    restart: always
    networks:
      - back_demo 
#    ports:
#      - "3307:3306"
    # volumes:
    #   - ./db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mysmartrootpassword
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmindemo
    networks:
      - back_demo
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - db

  drupal:
    container_name: kickstartdemo
    image: demo_commerce_kickstart_3
    networks:
      - front_demo
      - back_demo
    ports:
      - "81:80"
    depends_on:
      - db
    restart: always

volumes:
  db:

networks:
  front_demo: {}
  back_demo: {}
