services:

  db:
    image: mariadb
    restart: always
    networks:
      - back-tier 
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mysmartrootpassword
      MARIADB_DATABASE: drupal
      MARIADB_USER: drupal
      MARIADB_PASSWORD: drupal

  phpmyadmin:
    image: phpmyadmin
    networks:
      - back-tier
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

  drupal:
    image: mihaimiculescu/drupal_commerce_kickstart_3
    networks:
      - front-tier
      - back-tier
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

volumes:
  db:

networks:
  front-tier: {}
  back-tier: {}


